[package]
name = "f4n-wcf-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f4n-wcf-core = { path = "../core" }
f4n-wcf-visualizer = { path = "../visualizer" }
