on:
  pull_request:

  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        command:
          - clippy
          - fmt --check --quiet

    steps:
      - name: Clone and checkout into the repository
        uses: actions/checkout@v3

      - name: Prepare Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Cache Rust stuff
        uses: Swatinem/rust-cache@v2

      - name: Execute ${{ matrix.command }}
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.command }}

