on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        command:
          - clippy
          - fmt

    steps:
      - name: Clone and checkout into the repository
        uses: actions/checkout@v3

      - name: Prepare Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Swatinem/rust-cache@v2


      - name: Execute ${{ matrix.command }}
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.command }}

